name: Build and deploy ASP.Net Core app to Azure Web App - comp4952lab1marco

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build lab-1-zodiac.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish lab-1-zodiac.csproj -c Release -o ${{env.GITHUB_WORKSPACE}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.GITHUB_WORKSPACE}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2C70E6A6D30A41F596E9489C2467CECE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B1E1D9EBBF4642FFB22A3EDDDB3CEDC7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4D1E233E8D104C08987DB2167CDF26C9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'comp4952lab1marco'
          slot-name: 'Production'
          package: .
